package models

// DocumentPassage is a page-sized piece of a saved document, kept so questions can be answered
// across all of a user's documents. The search column (tsv) is generated by the database.
type DocumentPassage struct {
	ID         uint `gorm:"primaryKey"`
	DocumentID uint
	UserID     uint
	Ord        int
	Page       *int
	PageEnd    *int
	DocName    string
	Text       string
}
