package models

// DocumentPassage is a page-sized piece of a saved document, kept so questions can be answered
// across all of a user's documents. The search column (tsv) is generated by the database.
// Embedding is the passage's meaning as float32 bytes (nil until the AI service has embedded it),
// and EmbeddingModel names the model that made it.
type DocumentPassage struct {
	ID             uint `gorm:"primaryKey"`
	DocumentID     uint
	UserID         uint
	Ord            int
	Page           *int
	PageEnd        *int
	DocName        string
	Text           string
	Embedding      []byte
	EmbeddingModel string
}
